<?php

namespace Plugin\ProductVideo42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ProductVideo42\Entity\ProductVideo;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProductVideoRepository.
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVideoRepository extends AbstractRepository
{
    /**
     * ProductVideoRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProductVideo::class);
    }
}
